### ISSUE TITLE
Suggestion for README.md  native & JVM pair cross build example

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/sbt-cross#13]
Again,  first of all, thank you for the examples & documentation.
I hope to help improve it by reporting my experiences.

To get my feet wet with cross building, I am following the
"Cross-compiling JVM and Native" section of the README.md.
It appears to me that the section "In build.sbt:" needs to start with:
```
import sbtcross.{crossProject, CrossType}
val sharedSettings = Seq(scalaVersion := "2.11.8") // Scala Native only supports 2.11
```
not simply:
```
val sharedSettings = Seq(scalaVersion := "2.11.8") // Scala Native only supports 2.11
```
I admit to being easily lead astray, but the comment `// (5) shadow sbt-scalajs' crossProject and CrossType until Scala.js 1.0.0 is released` lead me to believe that the import was only necessary  when sbt-scalajs was in use.  SBT soon disabused me of that notion.

Adding the import makes it easier for people to understand the intent and do a cut & paste
and have it be successful.  Happy campers!

Thank you

Lee

**Comment by LeeTibbert** [comment]
If the powers that be agree with this suggestion, would a pull request from me
be worth the overhead at your end? That is would it save effort or cost them?

**Comment by sjrd** [comment]
> lead me to believe that the import was only necessary when sbt-scalajs was in use. SBT soon disabused me of that notion.

Hum, your interpretation is definitely supposed to be correct. That import should not be necessary if your build does not (transitively) depend on `sbt-scalajs`. Could you provide a reproduction?

**Comment by LeeTibbert** [comment]
Sebastian,

Thank you for your timely & supportive query.

Reproducer is easy,  just cut & paste the text from
the sbt-cross README.md section for a
scala-native/JVM duo cross project.

In case I did not do a good job following the example, I will
attach mine. Please pardon the roughness.

Without the import line, sbt complains about crossProject
when it tries to parse the build.sbt file.  Adding the import
quiets that complaint, but it sounds like that is not the
intention.   (On my system, with the import sbt later blows up in the
update stage because it can not find 4 artifacts).

  ~/Sandbox/scala_native/crossJvmNative_2/build.sbt:20: error: not found:
value
  crossProject
    crossProject(JVMPlatform, NativePlatform)
  ^
  sbt.compiler.EvalException: Type error in expression

I hope this is useful.  Please let me know if you would like additional
information.

Once I have the native/JVM duo working, I hope to go on and do a
native/JVM/scalajs trio.

Lee



On Fri, Dec 2, 2016 at 2:07 AM, Sébastien Doeraene <notifications@github.com

**Comment by sjrd** [comment]
@MasseGuillaume I think this is a bug. It seems `crossProject` and `CrossType` are not available through the `CrossPlugin.autoImport` object. We should put them there.

**Comment by MasseGuillaume** [comment]
@LeeTibbert thanks for those early bug reports! I have a bugfix in this PR: https://github.com/scala-native/sbt-cross/pull/14
