### ISSUE TITLE
Support for triple cross project with Scala.Js

### ISSUE THREAD

**Issue by mkotsbak** [scala-native/sbt-cross#2]
It should be possible to build a triple build for both jvm, native and JS. Is that possible without adding a dependency on the sjs cross plugin/sjs? Maybe it is better to have another cross build plugin for that case?

**Comment by mkotsbak** [comment]
Well, that separate cross build plugin seems to exist already!:https://github.com/MasseGuillaume/sbt-multi-platforms

**Comment by densh** [comment]
This is on the roadmap! In fact Scala.js interop is the main reason why `sbtcrossproject` is a separate project that is not part of `scala-native/scala-native` monorepo.

**Comment by MasseGuillaume** [comment]
It's the 4th bullet point in: https://github.com/scala-native/scala-native/issues/58

**Comment by MasseGuillaume** [comment]
@densh 
fixed in https://github.com/scala-native/sbt-cross/pull/4
